Added support to devstack for: "redstack install" "redstack build" "redstack initialiaze"

diff --git a/lib/reddwarf b/lib/reddwarf
--- a/lib/reddwarf
+++ b/lib/reddwarf
@@ -33,58 +33,52 @@ function msgout() {
     return 0
 }
 
-# Defaults
-# --------
+# set up default directories
 REDDWARF_DIR=$DEST/reddwarf
 REDDWARFCLIENT_DIR=$DEST/python-reddwarfclient
+PACKAGES_DIR=/var/lib/packages/debian/
+BUILD_DIR=/tmp/build/
+PATH_INTEGRATION_CONF=/tmp/reddwarf-integration/
+PATH_ENV_CONF=$PATH_INTEGRATION_CONF/env.rc
+USERHOME=$HOME
 
-# set up default directories
+#REDDWARF_DATA_DIR=${REDDWARF_DATA_DIR:-${DATA_DIR}/reddwarf}
 
-# cleanup_reddwarf() - Remove residual data files, anything left over from previous
-# runs that a clean run would need to clean up
-function cleanup_reddwarf() {
-    local mod="cleanup_reddwarf"
-    # This function intentionally left blank
-    msgout "DEBUG" "$mod:<-- "
-    msgout "DEBUG" "$mod:--> "
+###############################################################################
+# Misc. tools
+###############################################################################
+
+function mysql_nova() {
+    echo mysql nova --execute "$@"
+    mysql -u root -p$DATABASE_PASSWORD nova --execute "$@"
 }
 
-# configure_reddwarfclient() - Set config files, create data dirs, etc
-function configure_reddwarfclient() {
-    local mod="configure_reddwarfclient"
-    msgout "DEBUG" "$mod<-- "    
-    setup_develop $REDDWARFCLIENT_DIR
-    msgout "DEBUG" "$mod:-->"
+function rd_manage() {
+    cd $REDDWARF_DIR
+    bin/reddwarf-manage --config-file=$USERHOME/reddwarf.conf $@
 }
 
-# configure_reddwarf() - Set config files, create data dirs, etc
-function configure_reddwarf() {
-    local mod="configure_reddwarf"
-    msgout "DEBUG" "$mod<-- ($REDDWARF_DIR)"    
-    setup_develop $REDDWARF_DIR
-
-    create_package_repo
-    munge_apache2
-    add_dbass_mycnf_to_package_repo
-
-    msgout "DEBUG" "$mod:-->"
-}
+ 
+###############################################################################
+# Misc helper functions
+###############################################################################
 
 function create_package_repo() {
     local mod="create_pacakge_repo"
     msgout "DEBUG" "$mod<-- "    
-    pkg_install reprepro apache2 bc debhelper
+    install_package reprepro apache2 bc debhelper
 
     # install the apt repo from /var/www
     # add distributions file to conf
     sudo mkdir -p $PACKAGES_DIR/{conf,incoming}
 
-    echo 'Origin: Rackspace
-Label: Rackspace
+    echo 'Origin: Openstack
+Label: Database as a Service Guest Agent
 Codename: squeeze
 Architectures: i386 amd64
 Components: main
-Description: Rackspace DBaaS APT Repository' | sudo tee $PACKAGES_DIR/conf/distributions
+Description: Openstack DBaaS Reddwarf APT Repository' | sudo tee $PACKAGES_DIR/conf/distributions
+
     msgout "DEBUG" "$mod:-->"
 }
 
@@ -125,18 +119,253 @@ function add_dbass_mycnf_to_package_repo() {
     cd $BUILD_DIR/dbaas-mycnf
     sudo -E ./builddeb.sh
     sudo -E reprepro -Vb $PACKAGES_DIR remove squeeze dbaas-mycnf
-    sudo -E reprepro --ignore=wrongdistribution -Vb $PACKAGES_DIR include squeeze *.changes
+    sudo -E reprepro --ignore=wrongdistribution --ignore=undefinedtarget -Vb $PACKAGES_DIR include squeeze *.changes
     msgout "DEBUG" "mod:-->"
 }
 
-# init_reddwarf() - Initialize database
-function init_reddwarf() {
-    local mod="init_reddwarf"
+function keystone_add_user() {
+    # Adds a user. Prints the UUID to standard out.
+    USER_NAME=$1
+    USER_PASS=$2
+    USER_EMAIL=$3
+    # Create the user "reddwarf"
+    USER_UUID=`keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN user-list | grep $USER_NAME | awk '{print $2}'`
+    if [ -z $USER_UUID ]; then
+        USER_UUID=`echo_id_from_table keystone \
+                   --endpoint http://localhost:35357/v2.0  \
+                   --token $SERVICE_TOKEN user-create \
+                   --name=$USER_NAME --pass="$USER_PASS" --email=$USER_EMAIL`
+    fi
+
+    echo $USER_UUID
+}
+
+function keystone_add_user_role() {
+    TENANT_UUID=$1
+    USER_UUID=$2
+    ROLE_UUID=$3
+    echo "keystone --endpoint http://localhost:35357/v2.0
+        --token $SERVICE_TOKEN user-role-add
+        --tenant_id $TENANT_UUID
+        --user $USER_UUID
+        --role $ROLE_UUID"
+    keystone --endpoint http://localhost:35357/v2.0 \
+        --token $SERVICE_TOKEN user-role-add \
+        --tenant_id $TENANT_UUID \
+        --user-id $USER_UUID \
+        --role-id $ROLE_UUID
+}
+
+function keystone_manage () {
+    keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN $@
+}
+
+function get_tenant_id() {
+    keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN tenant-list | grep $1 | awk '{print $2}'
+}
+
+function get_role_id() {
+    keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN role-list | grep $1 | awk '{print $2}'
+}
+
+function configure_keystone_for_reddwarf() {
+    msgout "DEBUG" "Configuring keystone..."
+
+    # Create the tenant "reddwarf".
+    # First we should check if these exist
+    REDDWARF_TENANT=`get_tenant_id reddwarf`
+    ADMIN_ROLE=`get_role_id admin`
+    if [ -z $REDDWARF_TENANT ]; then
+        REDDWARF_TENANT=`echo_id_from_table keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN tenant-create --name=reddwarf`
+    fi
+
+    REDDWARF_ROLE=`get_role_id reddwarf`
+    if [ -z "$REDDWARF_ROLE" ]; then
+        REDDWARF_ROLE=`echo_id_from_table keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN role-create --name=reddwarf`
+    fi
+
+    DAFFY_TENANT=`get_tenant_id daffy`
+    if [ -z $DAFFY_TENANT ]; then
+        DAFFY_TENANT=`echo_id_from_table keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN tenant-create --name=daffy`
+    fi
+
+    DAFFY_ROLE=`get_role_id daffy`
+    if [ -z "$DAFFY_ROLE" ]; then
+        DAFFY_ROLE=`echo_id_from_table keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN role-create --name=daffy`
+    fi
+
+    REDDWARF_USER=`keystone_add_user reddwarf REDDWARF-PASS reddwarf@example.com`
+
+    #TODO(tim.simpson): Write some code here that removes the roles so these
+    #                   command won't fail if you run them twice.
+    #                   That way we will still catch errors if our calls to
+    #                   keystone fail, but can run kickstart twice w/o install.
+    set +e
+
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $REDDWARF_ROLE
+
+    # TODO: Restrict permissions.
+    REDDWARF_USER=`keystone_add_user radmin radmin radmin@example.com`
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $REDDWARF_ROLE
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $ADMIN_ROLE
+
+    REDDWARF_USER=`keystone_add_user Boss admin boss@example.com`
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $REDDWARF_ROLE
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $ADMIN_ROLE
+
+    REDDWARF_USER=`keystone_add_user chunk chunk chunk@example.com`
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $REDDWARF_ROLE
+
+    REDDWARF_USER=`keystone_add_user daffy daffy daffy@example.com`
+    keystone_add_user_role $DAFFY_TENANT $REDDWARF_USER $DAFFY_ROLE
+
+    REDDWARF_USER=`keystone_add_user examples examples examples@example.com`
+    keystone_add_user_role $REDDWARF_TENANT $REDDWARF_USER $REDDWARF_ROLE
+
+    set -e
+
+    # Add the tenant id's into test.conf
+    # Commenting out for now since tests need to be part of tempest. 
+    # Will revisit when we need to enable tests.
+    # Add the tenant id's into test.conf
+    # DEMO_TENANT=`get_tenant_id demo`
+    # sed -i "s/%reddwarf_tenant_id%/$REDDWARF_TENANT/g" $USERHOME/test.conf
+    # sed -i "s/%daffy_tenant_id%/$DAFFY_TENANT/g" $USERHOME/test.conf
+    # sed -i "s/%demo_tenant_id%/$DEMO_TENANT/g" $USERHOME/test.conf
+
+    echo "
+REDDWARF_TENANT=$REDDWARF_TENANT
+REDDWARF_USER=$REDDWARF_USER
+REDDWARF_ROLE=$REDDWARF_ROLE
+" > $PATH_ENV_CONF
+
+    echo "
+# REDDWARF_TENANT=$REDDWARF_TENANT
+# REDDWARF_USER=$REDDWARF_USER
+# REDDWARF_ROLE=$REDDWARF_ROLE"
+
+    echo "Checking login..."
+    # Now attempt a login
+    curl -d '{"auth":{"passwordCredentials":{"username": "reddwarf", "password": "REDDWARF-PASS"},"tenantName":"reddwarf"}}' \
+     -H "Content-type: application/json" http://localhost:35357/v2.0/tokens
+
+    # Register reddwarf service.
+    SERVICE_UUID=`keystone_manage service-list | grep reddwarf | awk '{print $2}'`
+    if [ -z $SERVICE_UUID ]; then
+        OS_USERNAME=reddwarf \
+        OS_PASSWORD=REDDWARF-PASS \
+        OS_AUTH_URL='http://localhost:8779/v1.0/$(tenant_id)s' \
+        keystone_manage service-create --name=Reddwarf \
+                            --type=reddwarf\
+                            --description="Reddwarf"
+        service_id=`keystone --endpoint http://localhost:35357/v2.0 --token $SERVICE_TOKEN  service-list|grep Reddwarf|cut -d'|' -f2`
+        keystone_manage endpoint-create \
+               --region RegionOne --service-id $service_id \
+               --publicurl 'http://localhost:8779/v1.0/$(tenant_id)s' \
+               --adminurl 'http://localhost:8779/v1.0/$(tenant_id)s' \
+               --internalurl 'http://localhost:8779/v1.0/$(tenant_id)s'
+
+    fi
+
+}
+
+function service_report_log_directory {
+    # enable logging for the service when running in CI
+    if [ -n "$CI_RUN" ]; then
+        sed -i "s/#log_dir/log_dir/" $USERHOME/$1.conf
+        sed -i "s/#log_file/log_file/" $USERHOME/$1.conf
+        sed -i "s/\/integration\/report/$ESCAPED_REDSTACK_SCRIPTS\/\.\.\/report\//" $USERHOME/$1.conf
+    fi
+}
+
+function fix_rd_configfile() {
+    cd $REDDWARF_DIR
+    cp etc/reddwarf/reddwarf.conf.sample $USERHOME/reddwarf.conf
+    cp etc/reddwarf/reddwarf-taskmanager.conf.sample $USERHOME/reddwarf-taskmanager.conf
+
+    # Fix the tokens in the conf files
+    sed -i "s/f7999d1955c5014aa32c/$RABBIT_PASSWORD/g" $USERHOME/reddwarf.conf
+    sed -i "s/e1a2c042c828d3566d0a/$DATABASE_PASSWORD/g" $USERHOME/reddwarf.conf
+    sed -i "s/be19c524ddc92109a224/$SERVICE_TOKEN/g" $USERHOME/reddwarf.conf
+
+    service_report_log_directory reddwarf
+    service_report_log_directory reddwarf-taskmanager
+}
+
+function add_flavor() {
+    FLAVOR_NAME=$1
+    FLAVOR_ID=$2
+    FLAVOR_MEMORY_MB=$3
+    FLAVOR_ROOT_GB=$4
+    echo "Adding flavor $FLAVOR_ID ($FLAVOR_NAME), memory=$FLAVOR_MEMORY_MB, root_gb=$FLAVOR_ROOT_GB"
+    mysql_nova "INSERT INTO instance_types (name, id, memory_mb, vcpus, deleted, ephemeral_gb, rxtx_factor, flavorid, root_gb, disabled, is_public) VALUES('$FLAVOR_NAME', $FLAVOR_ID, $FLAVOR_MEMORY_MB, 1, 0, 40, 1, $FLAVOR_ID, $FLAVOR_ROOT_GB, 0, 1);"
+}
+
+function add_flavors() {
+    # Incredibly useful for testing resize in a VM.
+    set +e
+    add_flavor 'tinier' 6 506 10
+    # It can also be useful to have a flavor with 512 megs and a bit of disk space.
+    add_flavor 'm1.rd-tiny' 7 512 2
+    # Its also useful to have a slightly bigger flavor...
+    add_flavor 'm1.rd-smaller' 8 768 2
+    set -e
+}
+
+
+###############################################################################
+# stack.sh entry points
+###############################################################################
+
+# cleanup_reddwarfclient() - Remove residual data files, anything left over from previous
+# runs that a clean run would need to clean up
+function cleanup_reddwarfclient() {
+    local mod="cleanup_reddwarfclient"
+    # This function intentionally left blank
+    msgout "DEBUG" "$mod:<-- "
+    msgout "DEBUG" "$mod:--> "
+}
+
+# cleanup_reddwarf() - Remove residual data files, anything left over from previous
+# runs that a clean run would need to clean up
+function cleanup_reddwarf() {
+    local mod="cleanup_reddwarf"
+    # This function intentionally left blank
+    msgout "DEBUG" "$mod:<-- "
+    msgout "DEBUG" "$mod:--> "
+}
+
+# configure_reddwarfclient() - Set config files, create data dirs, etc
+function configure_reddwarfclient() {
+    local mod="configure_reddwarfclient"
     msgout "DEBUG" "$mod<-- "    
-    msgout "DEBUG" "mod:-->"
+    setup_develop $REDDWARFCLIENT_DIR
+    msgout "DEBUG" "$mod:-->"
 }
 
+# configure_reddwarf() - Set config files, create data dirs, etc
+function configure_reddwarf() {
+    local mod="configure_reddwarf"
+    msgout "DEBUG" "$mod<-- ($REDDWARF_DIR)"    
+    setup_develop $REDDWARF_DIR
+ 
+    # Set up redstack dependencies in addition to reddwarf dependencies
+    # Using ubuntu-vm builder temporarily. What is maven2 used for?
+    # TODO: This needs to be replaced by the tripleo package builder.
+    install_package ubuntu-vm-builder maven2
 
+    # Create the reddwarf data dir if it doesn't exist
+    sudo mkdir -p ${REDDWARF_DATA_DIR}
+    sudo chown -R $USER: ${REDDWARF_DATA_DIR}
+    
+    create_package_repo
+    munge_apache2
+    add_dbass_mycnf_to_package_repo
+    
+    #init_reddwarf
+
+    msgout "DEBUG" "$mod:-->"
+}
 
 # install_reddwarfclient() - Collect source and prepare
 function install_reddwarfclient() {
@@ -154,11 +383,36 @@ function install_reddwarf() {
     msgout "DEBUG" "mod:-->"
 }
 
+# init_reddwarf() - Initializes Reddwarf Database as a Service
+function init_reddwarf() {
+    local mod="init_reddwarf"
+    msgout "DEBUG" "$mod<-- " 
+
+    msgout "DEBUG" "Creating reddwarf db..."
+    mysql_nova "DROP DATABASE IF EXISTS reddwarf;"
+    mysql_nova "CREATE DATABASE reddwarf;"
+   
+    mkdir -p $PATH_INTEGRATION_CONF
+
+    msgout "DEBUG" "Creating Keystone users..."
+    configure_keystone_for_reddwarf
+
+    msgout "DEBUG" "Making a temporary reddwarf config file..."
+    fix_rd_configfile
+
+    msgout "DEBUG" "Initializing the Reddwarf Database..."
+    rd_manage db_sync
+
+    msgout "DEBUG" "Adding reddwarf specific flavours..."
+    add_flavors
+
+    msgout "DEBUG" "mod:-->"
+}
+
 # start_reddwarf() - Start running processes, including screen
 function start_reddwarf() {
     local mod="start_reddwarf"
     msgout "DEBUG" "$mod<-- "    
-
     msgout "DEBUG" "mod:-->"
 }
 
@@ -166,7 +420,6 @@ function start_reddwarf() {
 function stop_reddwarf() {
     local mod="stop_reddwarf"
     msgout "DEBUG" "$mod<-- "    
-
     msgout "DEBUG" "mod:-->"
 
 }
